# -*- coding: utf-8 -*-
"""Amirthan210005005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zHFRGBojwCEXNPrgZyujl4yd2Y-B0VhT
"""

import pandas as pd
import numpy as np
from sklearn import linear_model

df1 = pd.read_csv('train.csv')
df1

reg = linear_model.LinearRegression()
reg.fit(df1[['CbRt','SGZ','P','Q','CrRl','AbRl','DfClb','DfRlRt','DfDfClb','ST1','ST2','ST3','ST4','DfST1','DfST2','DfST3','DfST4','Sa']],df1.Target)

reg.coef_

reg.intercept_

df2 = pd.read_csv('test.csv')
reg.predict(df2[['CbRt','SGZ','P','Q','CrRl','AbRl','DfClb','DfRlRt','DfDfClb','ST1','ST2','ST3','ST4','DfST1','DfST2','DfST3','DfST4','Sa']])

ind  = pd.read_csv('test.csv', usecols = [0])
ind

# Load Pandas
from pandas import DataFrame

# Load each file into a pandas dataframe, this is based on a numpy array
data1 = pd.read_csv('test.csv',sep=',',parse_dates=False)
outfile = open('submission8.csv','w')
np.savetxt("submission8.csv", data, delimiter=" ")
df3 = pd.read_csv('submission8.csv', header = None, names = ['Target','Id_'])

df3.to_csv('submission8.csv')


#Now add 'header5' from data1 to data2
#data1['Id'] = df3['Id_']

out = csv.writer(outfile)
out.writerows(map(lambda x: [x],data1['Id'] ))
outfile.close()

#Save it back to csv
df3.to_csv('output.csv', index = False)
sub1 = pd.read_csv('output.csv')
sub1

df3['Id_'] = data1['Id']
df3
#the required file is "submission8"

x = df1.drop('Target', axis = 1)
y = df1['Target']
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.15, random_state = 42)
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train_x, train_y)
reg.score(test_x, test_y)

reg.score(train_x, train_y)

lasso_reg = linear_model.Lasso(alpha = 0.000000000000000001, max_iter=10000000, tol=0.00001)
lasso_reg.fit(train_x, train_y)

lasso_reg.score(train_x, train_y)

lasso_reg.score(test_x, test_y)

from sklearn.linear_model import Ridge
ridge_reg = linear_model.Ridge(alpha = 0.00000000000000001, max_iter=1000000000, tol=0.001)
ridge_reg.fit(train_x, train_y)
ridge_reg.score(train_x, train_y)

ridge_reg.score(test_x, test_y)

ridge_reg.fit(df1[['CbRt','SGZ','P','Q','CrRl','AbRl','DfClb','DfRlRt','DfDfClb','ST1','ST2','ST3','ST4','DfST1','DfST2','DfST3','DfST4','Sa']],df1.Target)
data1 = ridge_reg.predict(df2[['CbRt','SGZ','P','Q','CrRl','AbRl','DfClb','DfRlRt','DfDfClb','ST1','ST2','ST3','ST4','DfST1','DfST2','DfST3','DfST4','Sa']])



test = pd.read_csv('test.csv',sep=',',parse_dates=False)
outfile = open('submission(ridge).csv','w')
np.savetxt("submission(ridge).csv", data1, delimiter=" ")
df3 = pd.read_csv('submission(ridge).csv', header = None, names = ['Target', 'Id'])

df3['Id'] = test['Id']

df3.to_csv('output.csv', index = False)

#Save it back to csv
#df3.to_csv('output.csv', index = False)
sub1 = pd.read_csv('output.csv')
sub1

lasso_reg.fit(df1[['CbRt','SGZ','P','Q','CrRl','AbRl','DfClb','DfRlRt','DfDfClb','ST1','ST2','ST3','ST4','DfST1','DfST2','DfST3','DfST4','Sa']],df1.Target)
data2 = lasso_reg.predict(df2[['CbRt','SGZ','P','Q','CrRl','AbRl','DfClb','DfRlRt','DfDfClb','ST1','ST2','ST3','ST4','DfST1','DfST2','DfST3','DfST4','Sa']])



test = pd.read_csv('test.csv',sep=',',parse_dates=False)
outfile = open('submission(lasso).csv','w')
np.savetxt("submission(lasso).csv", data2, delimiter=" ")
df3 = pd.read_csv('submission(lasso).csv', header = None, names = ['Target', 'Id'])

df3['Id'] = test['Id']

df3.to_csv('output.csv', index = False)

#Save it back to csv
#df3.to_csv('output.csv', index = False)
sub1 = pd.read_csv('output.csv')
sub1

bey_reg = linear_model.BayesianRidge(n_iter = 30000000, tol = 0.001, alpha_1=0.00001)
bey_reg.fit(train_x, train_y)
bey_reg.score(test_x, test_y)
#data3 = bey_reg.predict(df2[['CbRt','SGZ','P','Q','CrRl','AbRl','DfClb','DfRlRt','DfDfClb','ST1','ST2','ST3','ST4','DfST1','DfST2','DfST3','DfST4','Sa']])

#data3

test = pd.read_csv('test.csv',sep=',',parse_dates=False)
outfile = open('submission(bey).csv','w')
np.savetxt("submission(bey).csv", data3, delimiter=" ")
df3 = pd.read_csv('submission(bey).csv', header = None, names = ['Target', 'Id'])

df3['Id'] = test['Id']

df3.to_csv('output.csv', index = False)

#Save it back to csv
#df3.to_csv('output.csv', index = False)
sub1 = pd.read_csv('output.csv')
sub1

data2 = lasso_reg.predict(df2[['CbRt','SGZ','P','Q','CrRl','AbRl','DfClb','DfRlRt','DfDfClb','ST1','ST2','ST3','ST4','DfST1','DfST2','DfST3','DfST4','Sa']])



test = pd.read_csv('test.csv',sep=',',parse_dates=False)
outfile = open('submission(lasso).csv','w')
np.savetxt("submission(lasso).csv", data2, delimiter=" ")
df3 = pd.read_csv('submission(lasso).csv', header = None, names = ['Target', 'Id'])

df3['Id'] = test['Id']

df3.to_csv('output.csv', index = False)

#Save it back to csv
#df3.to_csv('output.csv', index = False)
sub1 = pd.read_csv('output.csv')
sub1